# Generated by Django 4.2.11 on 2024-04-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("logo", models.ImageField(upload_to="")),
                ("desc", models.CharField(max_length=500)),
                ("link", models.URLField()),
            ],
        ),
    ]
