# Generated by Django 4.2.11 on 2024-04-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DevOpsStats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="collectedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_url", models.URLField()),
                ("project_extensions", models.TextField()),
            ],
        ),
    ]
