# Generated by Django 4.2.11 on 2024-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DevOpsStats", "0002_collecteddata"),
    ]

    operations = [
        migrations.CreateModel(
            name="newServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("logo", models.ImageField(upload_to="")),
                ("desc", models.CharField(max_length=500)),
                ("link", models.URLField()),
            ],
        ),
    ]
